name: ci

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: cache
              id: cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}

            - run: npm ci
              if: steps.cache.outputs.cache-hit != 'true'

            - name: set-changed-files
              id: files
              uses: jitterbit/get-changed-files@v1
              continue-on-error: true

            - name: npm run test
              run: npm run test ${{ steps.files.outputs.all }}
