name: conversor

on:
    push:
        branches: [main]

    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'info'
            projects:
                required: true
                description: 'Project names to be converted, separated by space'

jobs:
    build:
        runs-on: ubuntu-latest
        
        services:
          redis:
            image: redis
            ports:
              - 6379:6379
            options: >-
              --health-cmd "redis-cli ping"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
              --entrypoint redis-server

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: cache-dependence
              uses: actions/cache@v2
              id: cache-dependence
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}

            - name: install dependence
              if: steps.cache-dependence.outputs.cache-hit != 'true'
              run: npm install

            - name: set-current-changed-files
              if: github.event.inputs.projects == ''
              id: changed-files
              uses: jitterbit/get-changed-files@v1
              continue-on-error: true

            - name: set-files-for-automatic-run
              if: github.event.inputs.projects == ''
              run: echo "files=${{ steps.changed-files.outputs.all }}" >> $GITHUB_ENV

            - name: set-files-for-manual-action
              if: github.event.inputs.projects != ''
              # run: echo "files=${{ github.event.inputs.projects }}" >> $GITHUB_ENV
              run: find catalog -type d -regex ".*/${{ github.event.inputs.projects }}[^/]*" | xargs echo "files=$1" >> $GITHUB_ENV

            - name: run conversor json
              run: npm run conversor:json ${{ env.files }}
              env:
                  LOG_LEVEL: ${{ github.event.inputs.logLevel }}
                  REDIS_HOST: localhost
                  REDIS_PORT: 6379

            - name: change to json branch
              uses: actions/checkout@v2
              with:
                  ref: json
                  clean: false

            - name: remove old files
              run: |
                  for project in ${{ github.event.inputs.projects }}; do
                    rm -rf "./catalog/${project}"
                  done

            - name: add new files
              run: cp -RT ./dist/catalog/ ./catalog/

            - name: set-current-date
              run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

            - name: add changes to json branch
              uses: EndBug/add-and-commit@v7
              with:
                  message: ${{ env.date }} ${{ github.sha }}
                  add: ./catalog
                  branch: json
