name: conversor-json

on:
    push:
        branches: [main]

jobs:
    convert-to-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "14"

            - name: cache-dependence
              uses: actions/cache@v2
              id: cache-dependence
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}

            - name: install dependence
              if: steps.cache-dependence.outputs.cache-hit != 'true'
              run: npm install

            # - name: get changed files
            #   id: files
            #   uses: jitterbit/get-changed-files@v1
            #   continue-on-error: true

            - name: convert markdown files to json
              run: npm run conversor:json

            - name: change to json branch
              uses: actions/checkout@v2
              with:
                  ref: json
                  clean: false

            - name: post-run of json conversor
              run: npm run conversor:json:post-run

            - name: Commit changes to json branch
              uses: EndBug/add-and-commit@v7
              with:
                  message: ${{ github.event.head_commit.message }} ${{ github.sha }}
                  add: .
                  remove: '["./catalog/**/*.md"]'
                  branch: json
