name: conversor

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: cache
              uses: actions/cache@v2
              id: cache
              with:
                  path: node_modules
                  key: ${{ hashFiles('package-lock.json') }}

            - name: set-current-date
              run: echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

            - name: install dependence
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install

            - name: conversor
              run: npm run conversor:json

            - name: checkout-json-branch
              uses: actions/checkout@v2
              with:
                  ref: json
                  clean: false

            - name: remove-old-catalog
              run: rm -rf ./catalog/*

            - name: add-new-catalog
              run: cp -r ./.baka/* ./catalog

            - name: generate-summary
              run: npm run generate:summary

            - name: commit-changes-to-json-branch
              uses: EndBug/add-and-commit@v7
              with:
                  message: ${{ env.date }} ${{ github.sha }}
                  add:
                    ./catalog
                    ./summary

                  branch: json
